os: osx

before_install:
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

before_script:
  - export PATH=$PATH:depot_tools
  - python scripts/bootstrap.py
  - gclient sync
  - gn gen out/release --args="angle_enable_gl=false is_debug=false"

jobs:
  include:
  - name: "ios xcode 9.4"
    python: "3.5"
    env: CMD="xcodebuild -project ios/xcode/OpenGLES.xcodeproj -target MetalANGLE -configuration Release"
    osx_image: xcode9.4
  - name: "ios xcode 11.2"
    python: "3.5"
    env: CMD="xcodebuild -project ios/xcode/OpenGLES.xcodeproj -target MetalANGLE -configuration Release"
    osx_image: xcode11.2
  - name: "macos xcode 9.4"
    python: "3.5"
    env: CMD="ninja -C out/release hello_triangle"
    osx_image: xcode9.4
  - name: "macos xcode 11.2"
    python: "3.5"
    env: CMD="ninja -C out/release hello_triangle"
    osx_image: xcode11.2

script:
  - $CMD
