name: C/C++ CI

on:
  push:
    branches: [ master, ci-temp, ci-temp2 ]
  pull_request:
    branches: [ master ]

jobs:
  build_gn:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
    - name: prerequisite tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git depot_tools
        echo "$PWD/depot_tools" >> $GITHUB_PATH
        gem install xcpretty
    - name: gclient sync
      run: |
        python scripts/bootstrap.py
        gclient sync
    - name: gn gen
      run: gn gen out/release --args="angle_enable_gl=false is_debug=false strip_absolute_paths_from_debug_symbols=true"
    - name: make
      run: ninja -C out/release angle_end2end_tests angle_deqp_gles2_tests hello_triangle
